modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"
issueTrackerURL="https://github.com/RenaatiuX/Dinos-Expansion/issues"
[[mods]]
    modId="dinosexpansion"
    version="${file.jarVersion}"
    displayName="Dinos Expansion" #mandatory
    #displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
    logoFile="examplemod.png"
    credits="To Coffeine and IntelliJ"
    authors="Bretzelfresser, RenatiuX"
    description='''This mod adds plents of dinos and a completely new Dino Dimension'''
[[dependencies.dinosexpansion]] #optional
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dinosexpansion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dinosexpansion]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.0.104,)"
    ordering="BEFORE"
    side="BOTH"